# Generated by Django 4.1.5 on 2023-03-26 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firereport', '0002_firetequesthistory_assignto'),
    ]

    operations = [
        migrations.AddField(
            model_name='firereport',
            name='AssignBy',
            field=models.IntegerField(default=0),
        ),
    ]
