# Generated by Django 4.1.5 on 2023-03-26 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firereport', '0003_firereport_assignby'),
    ]

    operations = [
        migrations.AddField(
            model_name='firetequesthistory',
            name='AssignBy',
            field=models.IntegerField(default=0),
        ),
    ]
