# Generated by Django 4.1.5 on 2023-03-26 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firereport', '0004_firetequesthistory_assignby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firetequesthistory',
            name='AssignBy',
            field=models.IntegerField(default=14),
        ),
    ]
