# Generated by Django 4.1.5 on 2023-03-27 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firereport', '0005_alter_firetequesthistory_assignby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firereport',
            name='UpdationDate',
        ),
        migrations.AddField(
            model_name='firereport',
            name='Account_id',
            field=models.IntegerField(default=0),
        ),
    ]
