# Generated by Django 4.1.5 on 2023-03-27 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firereport', '0006_remove_firereport_updationdate_firereport_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='firereport',
            name='UpdationDate',
            field=models.DateTimeField(null=True),
        ),
    ]
