# Generated by Django 4.1.5 on 2023-04-06 07:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('firereport', '0008_userdepartment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdepartment',
            old_name='customer',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='userdepartment',
            name='department',
            field=models.CharField(choices=[('admin', 'Administrator'), ('stock', 'Stockist'), ('eng', 'Engineers'), ('finance', 'Finance')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
