# Generated by Django 4.1.5 on 2023-04-06 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firereport', '0009_rename_customer_userdepartment_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDepartment',
        ),
    ]
