# Generated by Django 4.1.5 on 2023-04-08 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firereport', '0010_delete_userdepartment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firetequesthistory',
            name='AssignBy',
            field=models.IntegerField(default=0),
        ),
    ]
