# Generated by Django 4.1.5 on 2023-04-23 05:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('039e88d2-0106-43e2-95be-96b6302e91a2'), primary_key=True, serialize=False),
        ),
    ]
