# Generated by Django 4.1.5 on 2023-04-23 05:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_customer_cust_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('0b5f6326-440a-4df9-8102-d5982f824b32'), primary_key=True, serialize=False),
        ),
    ]
