# Generated by Django 4.1.5 on 2023-04-23 05:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_customer_cust_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('df3c8026-b7e2-42bb-ac18-5150401aec5f'), primary_key=True, serialize=False),
        ),
    ]
