# Generated by Django 4.1.5 on 2023-04-25 10:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_customer_cust_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('73241b7e-06a8-4493-b2cd-e07810c6b168'), primary_key=True, serialize=False),
        ),
    ]
