# Generated by Django 4.1.5 on 2023-04-25 10:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_customer_cust_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('0e19bf29-93f6-4c59-9082-7350a9080835'), primary_key=True, serialize=False),
        ),
    ]
