# Generated by Django 4.1.5 on 2023-04-25 16:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_alter_customer_cust_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('ad4115c5-e3f2-47eb-8337-a29f5918f0fb'), primary_key=True, serialize=False),
        ),
    ]
