# Generated by Django 4.1.5 on 2023-05-05 04:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_alter_customer_cust_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('7b2ae2bc-d4c4-4ded-82f7-5f642efdfb65'), primary_key=True, serialize=False),
        ),
    ]
