# Generated by Django 4.1.5 on 2023-05-14 17:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_alter_customer_cust_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('4ae29d51-ddfd-432d-8da3-88afc1084932'), primary_key=True, serialize=False),
        ),
    ]
