# Generated by Django 4.2.1 on 2023-05-30 04:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_alter_customer_cust_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('ac455b16-6b64-44e9-a6e2-874af6b02a4e'), primary_key=True, serialize=False),
        ),
    ]
