# Generated by Django 3.1.4 on 2023-06-10 15:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_auto_20230610_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('59276086-f95b-42ef-9dcc-4c33f4682231'), primary_key=True, serialize=False),
        ),
    ]
