# Generated by Django 3.1.4 on 2023-06-10 16:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_auto_20230610_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('834cae4c-cae9-4632-adc3-ebc5e28e2467'), primary_key=True, serialize=False),
        ),
    ]
