# Generated by Django 3.1.4 on 2023-06-11 04:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0016_auto_20230610_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('37b19197-d82d-406e-a8f2-a5af285e318f'), primary_key=True, serialize=False),
        ),
    ]
