# Generated by Django 3.1.4 on 2023-06-11 12:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0017_auto_20230611_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('57e3053d-9d17-4111-af09-24d0c9c60e9e'), primary_key=True, serialize=False),
        ),
    ]
