# Generated by Django 3.1.4 on 2023-06-11 13:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0018_auto_20230611_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('d76abe48-ab9e-4466-ba67-6f971b751dc5'), primary_key=True, serialize=False),
        ),
    ]
