# Generated by Django 3.1.4 on 2023-06-11 15:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0019_auto_20230611_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('22783974-eb53-42d1-99d2-caee4d4f099c'), primary_key=True, serialize=False),
        ),
    ]
