# Generated by Django 3.1.4 on 2023-06-12 05:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0021_auto_20230611_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('4ba7bbc3-969d-4805-8c66-b1cf6b17810d'), primary_key=True, serialize=False),
        ),
    ]
