# Generated by Django 3.1.4 on 2023-06-12 05:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0022_auto_20230612_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('587e69c7-ef6e-4b16-9b4b-c4f626b00383'), primary_key=True, serialize=False),
        ),
    ]
