# Generated by Django 3.1.4 on 2023-06-15 11:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0025_auto_20230615_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('79bc1407-2ed1-4ff2-8cdb-ad560cc46a5c'), primary_key=True, serialize=False),
        ),
    ]
