# Generated by Django 3.1.4 on 2023-06-15 12:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0026_auto_20230615_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('a61884f2-d05f-4322-9152-365d4a5e5612'), primary_key=True, serialize=False),
        ),
    ]
