# Generated by Django 3.1.4 on 2023-06-15 12:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0027_auto_20230615_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('3c59a3a5-4c56-454e-88db-3a91b297ca9e'), primary_key=True, serialize=False),
        ),
    ]
