# Generated by Django 3.1.4 on 2023-06-15 15:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0028_auto_20230615_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('3a3c2e82-22ee-4449-bab4-933c92bf9580'), primary_key=True, serialize=False),
        ),
    ]
