# Generated by Django 3.1.4 on 2023-06-16 09:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0029_auto_20230615_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('521f6bfb-5bc6-4630-b913-d5f876ab243b'), primary_key=True, serialize=False),
        ),
    ]
