# Generated by Django 3.1.4 on 2023-06-16 10:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0030_auto_20230616_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('e574fb82-0b72-472d-b8e4-7bd5515e953a'), primary_key=True, serialize=False),
        ),
    ]
