# Generated by Django 3.1.4 on 2023-06-16 11:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0031_auto_20230616_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('70377ec5-cb41-4d91-9dcc-ab88236d0913'), primary_key=True, serialize=False),
        ),
    ]
