# Generated by Django 3.1.4 on 2023-06-16 13:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0033_auto_20230616_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('18f40f1e-ed62-455b-b32e-a830041cd1c5'), primary_key=True, serialize=False),
        ),
    ]
