# Generated by Django 3.1.4 on 2023-06-16 13:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0034_auto_20230616_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('1807840e-2526-42c0-9689-23641ca8dcfe'), primary_key=True, serialize=False),
        ),
    ]
