# Generated by Django 3.1.4 on 2023-06-16 15:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0035_auto_20230616_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('9d7d53c6-eb22-4706-85a8-403178393923'), primary_key=True, serialize=False),
        ),
    ]
