# Generated by Django 3.1.4 on 2023-06-16 15:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0036_auto_20230616_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('6b4ea0af-2951-4eb4-942e-6724386621eb'), primary_key=True, serialize=False),
        ),
    ]
