# Generated by Django 3.1.4 on 2023-06-16 15:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0037_auto_20230616_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('8015b5bc-f1c3-4afb-b963-861593deba4e'), primary_key=True, serialize=False),
        ),
    ]
