# Generated by Django 3.1.4 on 2023-06-16 15:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0038_auto_20230616_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('49b4d32d-6a29-4c7a-b312-414222526b8c'), primary_key=True, serialize=False),
        ),
    ]
