# Generated by Django 3.1.4 on 2023-06-16 16:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0040_auto_20230616_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('d6382c1f-94bf-4843-ba88-001cd72ae259'), primary_key=True, serialize=False),
        ),
    ]
