# Generated by Django 3.1.4 on 2023-06-16 16:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0041_auto_20230616_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('a837000f-2bce-4660-8226-702a9876bf29'), primary_key=True, serialize=False),
        ),
    ]
