# Generated by Django 3.1.4 on 2023-06-16 16:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0043_auto_20230616_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('d73df08e-07c0-469a-924e-4ee19909a167'), primary_key=True, serialize=False),
        ),
    ]
