# Generated by Django 3.1.4 on 2023-06-16 16:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0044_auto_20230616_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('a7b4654c-2115-4512-b5c5-1150eb1ef486'), primary_key=True, serialize=False),
        ),
    ]
