# Generated by Django 3.1.4 on 2023-06-16 16:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0045_auto_20230616_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('2262d7eb-9fe5-49fb-9c0a-aeb6dac02ef5'), primary_key=True, serialize=False),
        ),
    ]
