# Generated by Django 3.1.4 on 2023-06-16 16:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0047_auto_20230616_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('1d3855e3-23a0-4a9c-990b-443c13851f01'), primary_key=True, serialize=False),
        ),
    ]
