# Generated by Django 3.1.4 on 2023-06-16 16:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0048_auto_20230616_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('9ad2182a-a35b-468d-b8bf-2fcc756a5d93'), primary_key=True, serialize=False),
        ),
    ]
