# Generated by Django 3.1.4 on 2023-06-16 17:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0050_auto_20230616_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('d0c177df-d514-455e-994f-33f8ad327bb0'), primary_key=True, serialize=False),
        ),
    ]
