# Generated by Django 3.1.4 on 2023-06-16 17:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0051_auto_20230616_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('7f3c2bdd-429b-4570-9efa-448162d16c81'), primary_key=True, serialize=False),
        ),
    ]
