# Generated by Django 3.1.4 on 2023-06-16 17:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0052_auto_20230616_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('91af896a-0c44-4cdf-a49b-5967412468a7'), primary_key=True, serialize=False),
        ),
    ]
