# Generated by Django 3.1.4 on 2023-06-16 17:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0053_auto_20230616_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('fdf3df58-a45b-4484-ad86-99a4f825390d'), primary_key=True, serialize=False),
        ),
    ]
