# Generated by Django 3.1.4 on 2023-06-16 17:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0054_auto_20230616_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('b00331e0-eb38-4695-a421-468f309f4036'), primary_key=True, serialize=False),
        ),
    ]
