# Generated by Django 3.1.4 on 2023-06-16 17:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0056_auto_20230616_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('0f2b7159-e93d-4f73-bf07-2eb370ab774a'), primary_key=True, serialize=False),
        ),
    ]
