# Generated by Django 3.1.4 on 2023-06-16 17:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0057_auto_20230616_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('cea55bac-520b-4dfa-b4b7-0f39033511be'), primary_key=True, serialize=False),
        ),
    ]
