# Generated by Django 3.1.4 on 2023-06-16 17:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0059_auto_20230616_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('4c52d30e-764c-41a7-8031-847c5d1bff14'), primary_key=True, serialize=False),
        ),
    ]
