# Generated by Django 3.1.4 on 2023-06-17 13:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0061_auto_20230617_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('136ee311-3de1-4348-9268-23ea8fb23716'), primary_key=True, serialize=False),
        ),
    ]
