# Generated by Django 3.1.4 on 2023-06-17 13:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0062_auto_20230617_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('3bec0e41-db1b-4fab-b0f5-d31e34bb4469'), primary_key=True, serialize=False),
        ),
    ]
