# Generated by Django 3.1.4 on 2023-06-17 13:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0063_auto_20230617_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('77cd7e16-9317-4122-be89-4551f36e1555'), primary_key=True, serialize=False),
        ),
    ]
