# Generated by Django 3.1.4 on 2023-06-17 13:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0064_auto_20230617_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('c61a00b0-ec54-4704-8020-7277d031eff9'), primary_key=True, serialize=False),
        ),
    ]
