# Generated by Django 3.1.4 on 2023-06-17 13:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0065_auto_20230617_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('33e22a81-6e91-4062-a952-5e0358523a64'), primary_key=True, serialize=False),
        ),
    ]
