# Generated by Django 3.1.4 on 2023-06-17 13:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0066_auto_20230617_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('8dead939-46ec-4320-9dea-395d1ce4d866'), primary_key=True, serialize=False),
        ),
    ]
