# Generated by Django 3.1.4 on 2023-06-17 14:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0067_auto_20230617_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('d07e2a61-507b-4319-a522-e2a573b56737'), primary_key=True, serialize=False),
        ),
    ]
