# Generated by Django 3.1.4 on 2023-06-17 15:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0069_auto_20230617_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('4deb0d00-f88c-428f-8f20-e7d7feebc37b'), primary_key=True, serialize=False),
        ),
    ]
