# Generated by Django 3.1.4 on 2023-06-17 15:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0071_auto_20230617_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('e69cd07d-4cf5-40e2-92ba-11af908fb594'), primary_key=True, serialize=False),
        ),
    ]
