# Generated by Django 3.1.4 on 2023-06-17 17:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0072_auto_20230617_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('e25bd0c4-3db1-47af-9f92-3fffb0a7ed3d'), primary_key=True, serialize=False),
        ),
    ]
