# Generated by Django 3.1.4 on 2023-06-18 05:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0077_auto_20230618_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('24800bb7-7aea-4de6-8b13-3d9718f34f09'), primary_key=True, serialize=False),
        ),
    ]
