# Generated by Django 3.1.4 on 2023-06-18 05:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0078_auto_20230618_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('585fd671-afc2-4b3a-a6b8-b9882041312c'), primary_key=True, serialize=False),
        ),
    ]
