# Generated by Django 3.1.4 on 2023-06-18 06:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0079_auto_20230618_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('6ab41813-a7b4-45cc-975e-895e3e274609'), primary_key=True, serialize=False),
        ),
    ]
