# Generated by Django 3.1.4 on 2023-06-18 10:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0080_auto_20230618_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('1c127f6b-3fe5-4046-a161-83551d06a63d'), primary_key=True, serialize=False),
        ),
    ]
