# Generated by Django 3.1.4 on 2023-06-18 14:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0081_auto_20230618_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('b62d1747-38c2-4f1f-ad4f-7ca6b43ae664'), primary_key=True, serialize=False),
        ),
    ]
