# Generated by Django 3.1.4 on 2023-06-20 12:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0082_auto_20230618_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('c9f58008-cd02-4879-aef7-bbad27998faf'), primary_key=True, serialize=False),
        ),
    ]
