# Generated by Django 3.1.4 on 2023-06-20 13:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0083_auto_20230620_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('3cee8a23-666d-4836-bf49-174960e6af77'), primary_key=True, serialize=False),
        ),
    ]
