# Generated by Django 3.1.4 on 2023-07-09 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0084_auto_20230620_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('1bdecc08-ccc7-4eef-9c3b-63a80f402704'), primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='customer_technical_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('meter_image', models.ImageField(upload_to='meter_images/')),
                ('netmeter_image', models.ImageField(upload_to='netmeter_images/')),
                ('abt_meter_image', models.ImageField(upload_to='abt_meter_images/')),
                ('ct_cubic_image', models.ImageField(upload_to='ct_cubic_images/')),
                ('AssignBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assign_by', to=settings.AUTH_USER_MODEL)),
                ('AssignTo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assign_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
