# Generated by Django 3.1.4 on 2023-07-09 06:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0085_auto_20230709_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('78ccbae7-af06-429f-8d45-70a9e924a546'), primary_key=True, serialize=False),
        ),
    ]
