# Generated by Django 3.1.4 on 2023-07-09 07:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0086_auto_20230709_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('b890436f-4cdd-494b-927c-6e855bb6903a'), primary_key=True, serialize=False),
        ),
    ]
