# Generated by Django 3.1.4 on 2023-07-22 09:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0088_auto_20230722_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('be725747-2ab6-45c6-abc6-11d7fc8441ef'), primary_key=True, serialize=False),
        ),
    ]
