# Generated by Django 3.1.4 on 2023-07-22 09:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0089_auto_20230722_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('f03362c8-0a55-418f-b662-1a3b26d79c8a'), primary_key=True, serialize=False),
        ),
    ]
