# Generated by Django 3.1.4 on 2023-07-22 09:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0090_auto_20230722_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('6ca4ae2f-d564-4839-9d9c-462e788705bc'), primary_key=True, serialize=False),
        ),
    ]
