# Generated by Django 3.1.4 on 2023-07-29 08:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0091_auto_20230722_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('87e664e3-6199-4313-b8ad-423cfdb09c40'), primary_key=True, serialize=False),
        ),
    ]
