# Generated by Django 3.1.4 on 2023-07-30 13:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0093_auto_20230729_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('bf6f3602-f24e-47f0-bbd6-a1520f321cbf'), primary_key=True, serialize=False),
        ),
    ]
