# Generated by Django 3.1.4 on 2023-07-30 14:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0094_auto_20230730_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('5e71ab01-e230-453b-97ce-83219df62184'), primary_key=True, serialize=False),
        ),
    ]
