# Generated by Django 3.1.4 on 2023-07-30 14:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0095_auto_20230730_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('09661a9d-3763-4a97-b0e6-6b2701cca271'), primary_key=True, serialize=False),
        ),
    ]
