# Generated by Django 3.1.4 on 2023-07-30 15:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0097_auto_20230730_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('8af38879-26ee-4e09-a5f8-076b9d013a96'), primary_key=True, serialize=False),
        ),
    ]
