# Generated by Django 3.1.4 on 2023-08-02 07:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0099_auto_20230730_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('df0e2cca-215c-4866-8d7d-78b07868f6da'), primary_key=True, serialize=False),
        ),
    ]
