# Generated by Django 3.1.4 on 2023-08-05 14:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0100_auto_20230802_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('3d841cef-f6a0-4210-864b-942af518e513'), primary_key=True, serialize=False),
        ),
    ]
