# Generated by Django 3.1.4 on 2023-08-19 04:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0102_auto_20230817_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('1a487d98-b68b-427e-8bde-9469c4d67298'), primary_key=True, serialize=False),
        ),
    ]
