# Generated by Django 3.1.4 on 2023-08-19 07:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0103_auto_20230819_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('2f0e96aa-b6c9-4d4e-a992-2905275fb35c'), primary_key=True, serialize=False),
        ),
    ]
