# Generated by Django 3.1.4 on 2023-08-20 16:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0104_auto_20230819_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('1e42a924-8bd6-4e6e-88df-753d781aa747'), primary_key=True, serialize=False),
        ),
    ]
