# Generated by Django 3.1.4 on 2023-08-27 12:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0105_auto_20230820_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('291018ea-a7c1-473a-a067-4c9ca366849c'), primary_key=True, serialize=False),
        ),
    ]
