# Generated by Django 3.1.4 on 2023-09-19 11:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0106_auto_20230827_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('045afb96-2667-4ec5-9d28-248844176be8'), primary_key=True, serialize=False),
        ),
    ]
