# Generated by Django 3.1.4 on 2023-09-19 12:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0107_auto_20230919_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_id',
            field=models.IntegerField(default=uuid.UUID('31977171-e5e4-416a-b2de-245cd062240c'), primary_key=True, serialize=False),
        ),
    ]
