# Generated by Django 3.1.4 on 2023-06-18 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detect_barcodes', '0001_initial'),
    ]

    operations = [
    ]
