# Generated by Django 3.1.4 on 2023-06-18 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('detect_barcodes', '0002_auto_20230618_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarcodeImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode_data', models.CharField(max_length=255)),
                ('file_saved_at', models.DateTimeField()),
                ('image', models.ImageField(upload_to='static/barcode_images')),
                ('barcode_type', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=255, null=True)),
                ('wattage', models.CharField(max_length=50, null=True)),
                ('barcode_path', models.ImageField(upload_to='static/barcode_images')),
                ('old_image', models.ImageField(null=True, upload_to='static/barcode_images')),
                ('company_name', models.CharField(max_length=255, null=True)),
                ('AssignTo', models.IntegerField(default=0)),
                ('AssignBy', models.IntegerField(default=0)),
            ],
        ),
    ]
