# Generated by Django 4.1.5 on 2023-01-29 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_order_id_alter_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer',
            new_name='customer',
        ),
    ]
