# Generated by Django 4.1.5 on 2023-03-13 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_staff_notification_staff_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff_notification',
            options={'verbose_name_plural': 'staff_Notification'},
        ),
    ]
