# Generated by Django 4.1.5 on 2023-03-13 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_staff_notification_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff_notification',
            options={},
        ),
    ]
