# Generated by Django 4.1.5 on 2023-03-13 14:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0011_alter_staff_notification_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='staff_Notification',
            new_name='Notification',
        ),
    ]
