# Generated by Django 4.1.5 on 2023-03-13 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_rename_notification_staff_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='staff_Notification',
        ),
    ]
