# Generated by Django 4.1.5 on 2023-04-14 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_alter_staff_notification_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_notification',
            name='is_current',
            field=models.BooleanField(default=True),
        ),
    ]
