# Generated by Django 4.1.5 on 2023-04-21 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=50, null=True)),
                ('DOB', models.DateField(null=True)),
                ('department', models.CharField(choices=[('Administration', 'Administration'), ('Stockist', 'Stockist'), ('Engineers', 'Engineers'), ('Finance', 'Finance')], max_length=50)),
                ('image', models.ImageField(blank=True, default='profile_images/default.png', null=True, upload_to='profile_pics')),
                ('designation', models.CharField(choices=[('Admin', 'Admin'), ('Sr.Cleark', 'Sr.Cleark'), ('Jr.Cleark', 'Jr.Cleark'), ('Accountant', 'Accountant'), ('Sr.Engg', 'Sr.Engg'), ('Jr.Engg', 'Jr.Engg')], max_length=50, null=True)),
                ('last_updated_by', models.PositiveIntegerField(null=True)),
                ('workphone', models.CharField(max_length=50, null=True)),
                ('bg', models.CharField(choices=[('O +ve', 'O +ve'), ('O -ve', 'O -ve'), ('A +ve', 'A +ve'), ('A -ve', 'A -ve'), ('B +ve', 'B +ve'), ('B -ve', 'B -ve'), ('AB +ve', 'AB +ve'), ('AB -ve', 'AB -ve')], max_length=50)),
                ('city', models.CharField(max_length=50, null=True)),
                ('taluka', models.CharField(max_length=50, null=True)),
                ('district', models.CharField(max_length=50, null=True)),
                ('pg', models.CharField(max_length=50, null=True)),
                ('institution', models.CharField(max_length=50, null=True)),
                ('yop', models.CharField(max_length=50, null=True)),
                ('specili', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('emraddress', models.CharField(max_length=50, null=True)),
                ('customer', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
