# Generated by Django 4.1.5 on 2023-04-25 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='yop',
            field=models.DateField(null=True),
        ),
    ]
